apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:D0Y2ZM/N0UXhTPhZ3m5x2wj+y6N0Nfns3lGcsA7HIgkkAmnfCbrXVSOWoiKx7xoPVgtTaK7U9Doe8lRE5Mq/cIkYag8CtRbHJtc0uOBCrjU3Ya5g3W8nUsdrdq2jcph630S47LS6PR9YvjjcQHGsK+qqt6dyHAJjdqB1+BJsGNgp8nvNsNt1BLcaTXACnWlVTbtcsfw+flSWb8XbvOqdvqPiTytbg5Z9H1k9OA6g7pB5uzCueq+u+Crrhx6FB7rRz1iAwLWC1zQW69y8JWCGHCYkiuT7b9bIXBM7pxDmYHfppBWAZeQJTmJ9H30=,iv:7CKoVcmpJhe37N59Vq30O96AFOHL/vwo+woEa+zMWdA=,tag:sC6j0P+zJjCM8CPyp/15ow==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVEEyZXFMVVJMaUUyc2tB
            NGpDMzBBT3FiaEliS0NLdW1ja0E3VzFIZkhJCkZaS1piMEhCdHp3aWtQMDI1VklK
            b2FUUEozS2wxKytDalppUDk4Q1I0bWsKLS0tIEdva1NDYnZTdVRLRXU4K0lHd2gr
            MjhaNENEL2ozcm5UaExSWnczYXdpcTQKUAbTKFdgeZHkjcg3fDvKB88AzwFFLXms
            HK0uDDhZmmqtWIy+aFAsSjE2bZWPMpllfyZoVzswiVKHtx0db6Lsig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2g8gz27h0dmmxkyleae975flrp3httmdyvjh6pf4p7yz5f5cfhqsjftvv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T01:31:53Z"
    mac: ENC[AES256_GCM,data:hIFdR8sAC5CyRne0yAQmBv0enKiijfqDUl6k/5w2aU/PspfS5hez7xXNKXcfMboYh8ONINl+/YUfw/NuHZ5im2HLf9iqlbd0aE4KerNI0U7IeFRqSKUrxDPZfpozlvNgx7PIcDPlQjDcLo3512SloApjngh4kbfoBeW8qs465m8=,iv:xdXamG1pn/ZIZ25w/qal+aVi2hVZNtqdGTUxK+NhV7U=,tag:cd/S4XAJPAz+za4le/2vaA==,type:str]
    version: 3.13.3
