apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: audiobookshelf
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              # Cloudflared has a /ready endpoint which returns 200 if and only if
              # it has an active connection to the edge.
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            # ConfigMap containing config.yaml
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true

            # Secret containing the tunnel credentials
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true

      volumes:
        # Secret containing the tunnel credentials
        - name: creds
          secret:
            secretName: tunnel-credentials

        # ConfigMap containing config.yaml
        - name: config
          configMap:
            name: cloudflared
            items:
              - key: config.yaml
                path: config.yaml

---
# This ConfigMap defines the cloudflared config.yaml file in Kubernetes.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: absthor

    credentials-file: /etc/cloudflared/creds/credentials.json

    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
      - hostname: absthor.itsmamoroso.com
        service: http://service-abs:3005

      # Debug rule
      - hostname: hello.example.com
        service: hello_world

      # Catch-all rule
      - service: http_status:404
