apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Z9m/Hds8nrjokK/xfNUlhF9iyxi4Ns/iH4FrrdDxDpXPfoY2kC9ER32fS0HZ0j8mCrasQ4AZs9d9aPAzYrk07YuY0QG3EhwumWmMooddS7r19uNkVzQEr3kSEz+XTfy2BlO/91GDJHdaospO7kq0XxLHsEENixEidePNM8x+QdJ94exhrZnhOWvk2ORbvYPei0iN5Lz6hJiCqR0oyoSX5DkzNiYrObZPwcHEoEQQw7TujtXsKkpvswfiQMt8dErNXxihxM2G/G/aWvi/WLzi3W48h8dK2RoQ42qlnP3LipWKyTjQx692uFCP7cg=,iv:6e1IgOq54GP4nIA0QNThtvYr6aL/3wRjq/fvKKKYPHE=,tag:Fa1oG0FYKPfP15HOqstnkQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcFExQWQ4ZVAwemNTTTF4
            WGh6eEQ4clJrUnIvNENVVHMwN09xKzlHUFRZCi9JT0x4T05aTEV3THNGSW9hVFR6
            eTJHbFU0WVY0QzV0R21iWXBkcXJXY2MKLS0tIGQzN3J6aGVKQVhSUFdtNlVSUFo5
            R1d4RDNhRklHTEFjclE0amZGUTVya00K54SMQuUQCC9sJwphaNl9NUquTu+zfwA5
            FXuw0jc85IKsPmJdnT6dMXDPxEDJRA4cJruIYppECiLRL2Iu/ghgqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2g8gz27h0dmmxkyleae975flrp3httmdyvjh6pf4p7yz5f5cfhqsjftvv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T14:32:02Z"
    mac: ENC[AES256_GCM,data:/uD9H464Kcoh3yCX1AhxLQDmOLSQqXCwkgG/3VY9QXXzjTrZ2u58wrYtyWSRRP/PP7SprzZS1fCZNopLROX8bpjTc6S6MRh0YmhJ4zMCdUFfYj4FZj7RwJEZKzvQNzcYSbpTubrI+Ddkd+P0eYeNbjjuXhkHmzuik8eETkVjsuk=,iv:DZ4+edCANrHpwV586tHG2AKZFxhT4ZBB2DSbJYzot0s=,tag:7IiNP8MX9z586EJHKqMxGQ==,type:str]
    version: 3.13.3
