apiVersion: v1
data:
    RENOVATE_TOKENd: ENC[AES256_GCM,data:qOI4gkKplcVTOSAlRKyYzjDnteaWyWO8qQ2U7mE+OG9aWLt+eI8cDGMWC55h/1EYe3fga79toO8=,iv:wNE0QdeRcfyio3QiBbWpfiv2l3zX11lcG5tjuO6Pvrs=,tag:8ZTIJt0lY/uTg5LsJr0BNA==,type:str]
kind: Secret
metadata:
    name: renovate-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdktYSmFnYXdXek9rRDcz
            Mk1vaVJZWHVJcFhxVzBLeThQZXpzZVlweUM0ClMwT04rMUpzREhEa0Y2OHFhVmh5
            V0hLVXNPUm5KeDdLQmxPK2puK2lmK0kKLS0tIGQ1TVFSTEltZmxMWUZERFB0YUo1
            YTRoWHZZY29CYjZUVjhoeU5jWFNaQ0UKr4zxkCVEvujdERvl0a1WRgcXXL56siaM
            e5QAEBS+rU2FWZEOSml8yxhBccIq1xZYaPbabUsl/z+TOR76Hl2orA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2g8gz27h0dmmxkyleae975flrp3httmdyvjh6pf4p7yz5f5cfhqsjftvv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T23:05:52Z"
    mac: ENC[AES256_GCM,data:lEHlA8AdlHXqAOrhPGtq2RX8HNZyGnNVxbWMXbm179fY7EmJsVoPzPKKk2V2hZm80AzxHEwFUAcl+9boU38/aHsQQfnl8S8FArT2J4pSLuMeNjPxk7m2EqeZI/Hn/SvWBF6+ut+ID6C3BEOUplO52Dnw+JYL7VgvdxaoGcUivAA=,iv:LEBMflIIpF3iaeIsKlkNE7Ez/NFVZ7idN+q5CGvpbKA=,tag:JAbomTYzIAFDYpYsNV/ilA==,type:str]
    version: 3.13.3
