apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:vqcC488nXib3+iGTCP6n14OBuSm6V1dY7b72RM/udkQr8s4UnxYWIcUYzMZjFhKdISQwQxcPDP0=,iv:54wByErn0y9da73dGG7dcUAQMG6woDyy2PoBnNeWHr8=,tag:EBTIpcJZTmMvtKHohxq3pA==,type:str]
kind: Secret
metadata:
    name: renovate-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTnpjZGJKaDAvci8rUmFw
            OTNDdmM1VnpIVHVSOXU2amNmT0VPVGxqbmo4CnFETmY2YzlyL1k1c2hzYW5URUpL
            dEU2YXRpYmFEL0FiNVVXUjcyT3VYVEEKLS0tIFk3bUxkZzBpTkxzTFAvT2RNM0tM
            akcrVlN2bkRIaFdDZEtRUk4yWEJ1aEEKZxUQhtyhCi9dRJ36kInYXu1HQz57FWug
            ldzuCesBrzNea72L3ld05EnkocOW3T/fKynRtzX3ssXbX8pbc7+q/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2g8gz27h0dmmxkyleae975flrp3httmdyvjh6pf4p7yz5f5cfhqsjftvv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:23:37Z"
    mac: ENC[AES256_GCM,data:j2/vWREbpUWRxtFU3OMS+yWV9rzDzc2wvPb5+hkJM7qsDk4XN5WB+YywRT9/ovKVy8nVC9evUtezB4U5vCnvep849fW80RpIH6uLeaNgAcatKXqNT+pvDqhVec2O4sbxpTUe3y1KiZt3oslcSbZCqD3S93MRDx07zdIwekO22QM=,iv:3+P9WmsK13quLSEXnCi8PFEBR5iQrmZz+UEJRYmGKZM=,tag:ENeAJHiDC8K5OlYVAt5+6w==,type:str]
    version: 3.13.3
