apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:+gMa5nym78o=,iv:XOk+5a4sCLKe+Mb0bpzN+Z/N84YSXyRzIaRPYYmFLzQ=,tag:hUyiYRDnEru3iKwAq3HSZA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:8KKV6f4/9NANjSIBN7Dp6eoiBTg0sBZp,iv:HUxmdpEk72sBYWeK1y8Zwxa4+KYBVP+mbCi/CsNi3po=,tag:wHfl2ac0eVEpulJe7wSk1w==,type:str]
kind: Secret
metadata:
    namespace: linkding
    name: linkding-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ejVjVEJmWkxCa3pHSTNB
            MXl2TlBSS3RvR2hEVE1ZY1lBWUsvMlQwZm40CkovYjBVSUFrVmk5VEFubWtiYUd3
            czZRK0hLYlQ5UkxYVWptc2liYkc0NGsKLS0tIE1BdGQxU0QwbDJyT1RxODBkd1hs
            NUN6MmVZTExLZkxjUk92dGtBV2pnWXMKKYexj7sbDN3gPO3OKk/ldqg9w7cUxB73
            4IC5aKr2xGrx/Tk1eW/VgOtaPLwFqckufpvf5IpjI/9nznE3Pzm6IQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2g8gz27h0dmmxkyleae975flrp3httmdyvjh6pf4p7yz5f5cfhqsjftvv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T15:39:42Z"
    mac: ENC[AES256_GCM,data:ipF7qh0pW7CtQMIQKCcSAIm2EtaDKa96StlDnxFrj/OU7dKVsucTD/M1z65zjR8X1YGv0aCfUl+kzceCSs9tv4s5O/R8eAKD553oHQ4hiTWHunXwqQHIdlYhbuALxs4aiklH+Rxbkuv76C/ZMOQDS3vf7s6OLyzHJZCNMlCK0JM=,iv:UnV9G02WRwK58IiBZGmFp98m6d5wv+rUjbOar7Qe2Es=,tag:k3tQgcmf62oN0na3xwfITQ==,type:str]
    version: 3.13.3
